---
title: "Data summary"
output: 
  rmarkdown::html_document:
    df_print: paged
    toc: true
    toc_depth: 3
    code_folding: hide
vignette: >
  %\VignetteIndexEntry{Data_summary}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

<style type="text/css">
.main-container {
  max-width: 1200px;
  margin-left: auto;
  margin-right: auto;
}
</style>

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  error = TRUE,
  comment = "#>",
  cache = FALSE, # don't put TRUE as inline chunk make R CMD check to crash
  cache.path = "cache/cache_vignette_data_summary/",
  fig.path = "figs/fig_vignette_data_summary/",
  fig.align = 'center'
)

library(rangeRinPA)

# set how to represent countries in plots:
#data_rangers$countryname <- countrycode(sourcevar = data_rangers$countryname_iso, "iso3c", "unicode.symbol")
#data_rangers$countryname[data_rangers$countryname_iso == "ZZZ"] <- "ZZZ"
#data_rangers$countryname[data_rangers$countryname_iso == "KOS"] <- "KOS"
data_rangers$countryname <- data_rangers$countryname_iso

# set overlap allowed in plots 
options("ggrepel.max.overlaps" = Inf)
```

```{r setup, message=FALSE}
library(sf)
library(dplyr)
library(tibble)
library(ggplot2)
library(forcats)
library(tidyr)
library(ggrepel)
library(spaMM)
library(countrycode)
library(gt)
```

## Rangers

### Distribution

Here are the countries sorted by number of rangers (mind the log scale):

```{r distribution rangers plot, fig.height=20}
data_rangers %>%
  filter(!is.na(staff_rangers)) %>%
  mutate(countryname_eng = fct_reorder(countryname_eng, staff_rangers)) %>%
  ggplot() +
    aes(x = staff_rangers, y = countryname_eng, fill = country_UN_continent) +
    geom_col(alpha = 0.5) +
    coord_trans(x = "log1p", expand = FALSE) +
    theme_minimal() +
    scale_x_continuous(breaks = c(0, 10, 100, 1000, 10000), minor_breaks = NULL) +
    labs(y = "Country", x = "Number of rangers") +
    theme(legend.position = "none", panel.grid.major.y = element_blank())
```

Info: colour represents continents.

**Note**: the distribution is highly skewed.

### Summary statistics

Here are the quantiles for the number of rangers:
```{r distribution rangers stats}
data_rangers %>%
  summarise(missing = sum(is.na(staff_rangers)),
            mean = mean(staff_rangers, na.rm = TRUE),
            median = median(staff_rangers, na.rm = TRUE),
            sd = sd(staff_rangers, na.rm = TRUE),
            quantile = list(quantile(staff_rangers, na.rm = TRUE))) %>%
  unnest_wider(quantile, names_sep = "_") %>%
  pivot_longer(cols = everything(), names_to = "statistic") %>%
  gt()
```

